### ISSUE TITLE
Use rectangle to indicate selected column, rather than dimming other columns

### ISSUE THREAD

**Issue by localsite** [USEPA/useeio-widgets#25]
#9 Avoid making the other columns dim because doing so prevents visually comparing the different intensities.

The intensity of the surrounding cells should not be changed when sorting by a column.
Place a rectangle around the selected column instead using css.

For example, choose GCC here and you'll see that it appears that Cement has only a moderate impact (pink) on Acid Rain and Smog. Whereas the reality is that it has a high impact (red) on both. Just because users are sorting does not mean they don't want to see the true levels of the other indicators. Adding a rectangle around the sorted column allows it to be highlighted without changing color intensities.

https://thetisiboth.github.io/useeio-widget-builds/sector_list.html#view=mosaic

CSS for placing rectangle on first indicator. (Add 2 to indicator in three places.)

```
<style>
    .sector-list .noborder {
        background-color: transparent;
    }
    .sector-list-table tbody td {
      position: relative;
    }
    .sector-list-table tbody tr:nth-child(1) td:nth-child(3):after {
        top: -4px;
        border-top: 1px solid #333;
    }
    .sector-list-table tbody tr:last-child td:nth-child(3):after {
        bottom: -4px;
        border-bottom: 1px solid #333;
    }
    .sector-list-table tbody td:nth-child(3):after {
      content: "";
      position: absolute;
      padding-leftX:1px;
      padding-right:6px;
      border-left: 1px solid #333;
      border-right: 1px solid #333;
      left: -4px;
      bottom: 0px;
      top: -2px;
      width: 100%;
      z-index: -1;
    }
 </style>
```

**Comment by TheTisiboth** [comment]
So I removed the extra transparency on non-sorted columns and added a rectangle on the sorted column. 
Then, the URL parameter `indicator` stay unused for the heatmap, and we can select the shown indicators with the parameter `view_indicators`

Is that the expected behavior?

[Screenshot](https://ibb.co/1ZKKyDb)

**Comment by localsite** [comment]
Looks great!  Here's css for the first column so the changing title size doesn't cause the heatmap to jump back-and-forth.

.sector-list-table thead td:first-child {
        max-width: 400px;
    }
    .sector-list-table tbody td:first-child {
        max-width: 400px;
        max-height: 30px;
        height: 30px;
        display: block;
        overflow: hidden;
        font-size: 12px;
    }
    .sector-list-table tbody td:first-child > div {
        overflow-x: scroll;
        height:44px;
    }
    .matrix-search {
        display: block;
        min-width: 400px;
        max-width: 400px;
    }
