### ISSUE TITLE
3. Auto check top 10 commodities in IOGrid

### ISSUE THREAD

**Issue by TheTisiboth** [USEPA/useeio-widgets#29]
3. When no sectors or naics are indicated, please auto-check the top 10 commodities in the center column. (Match the initial rows-per=page count.) This will allow the Upstream and Downstream columns to initially show ranked values (rather than defaulting alphabetically to Abrasive Products).

https://model.earth/io/build/slider.html#indicators=LAND,PEST

**Comment by TheTisiboth** [comment]
Should the url remain without the top 10 selected sectors?

**Comment by localsite** [comment]
This is where the hiddenhash would be used. Save the sectors or naics in the hiddenhash, and automatically trigger the other widgets to update when the hiddenhash changes. (We may need to save the hiddenhash object string in a hidden div to do this efficiently.)

In the JQuery frontend, URL values like show=bioeconomy will trigger specific naics values to be inserted into the hiddenhash.

For the indicator changes: Try updating the URL as the indicator changes, WITHOUT updating the URL history. Then the user won't have to click back dozens of times to return to the previous page. (Later we could make this a setting option: Retain URL history for each hash change.) You may want to post this paragraph as a unique issue.

**Comment by localsite** [comment]
Double check the sample widgets to make sure that the NAICS does not appear in the hash. 

Remove the sectors= value from links 5,6 and 7 and place in the config setting within each page instead.

https://thetisiboth.github.io/useeio-widget-builds/

(I currently have to load pages twice because the naics gets sent to the URL and triggers a hash change event.)

Thanks!

**Comment by TheTisiboth** [comment]
> 
> 
> Prevent links 5 and 7 from updating the hash.
> 
What do you mean with this ?

Yes, I am opening an new issue about the widget update : https://github.com/USEPA/useeio-widgets/issues/41

**Comment by LorenHeyns** [comment]
When the count is 20, auto check all 20.
https://thetisiboth.github.io/useeio-widget-builds/slider.html#count=20

**Comment by TheTisiboth** [comment]
So the 10 first commodities should be selected if no sectors are indicated, and the 20 first commodities should be selected if count = 20 is indicated. Is that all ?

**Comment by TheTisiboth** [comment]
And if the count is 30, what should happen ?

**Comment by modelearth** [comment]
The items displayed initially would all be checked. When clicking to the second pagination, none would be checked.

Also provide a means to check all using a hash value. Perhaps allsectors=true
