### ISSUE TITLE
Show multiple highlight-rectangles when there are multiple indicators chosen

### ISSUE THREAD

**Issue by localsite** [USEPA/useeio-widgets#30]
When multiple indicators are in the hash, please show rectangles around multiple columns.
(When there are multiple indicators, the sort order is driven by all the selected indicators.)

Now that "view_indicators" is used to limit the view to specific columns, the "indicators" parameter can be used to sort by specific columns when the entire heatmap is displayed.

Example: use indicators=ACID,ENRG to highlight two columns while continuing to show all the heatmap columns.

https://thetisiboth.github.io/useeio-widget-builds/sector_list.html?indicators=ACID,ENRG

This relates to the last sentence in update #8. You implemented the first part on Friday. Thanks!

8. We need to show all the heatmap columns even when the io grid above it is limited to specific indicators.
The heatmap's existing indicators parameter could be renamed to view_indicators.
The indicators parameter would still be used to sort the heatmap.

**Comment by localsite** [comment]
Unselect all the existing columns when clicking a new column.

We will use the hash value to select multiple column.

**Comment by TheTisiboth** [comment]
Oh ok it was not clear for me, I thought the behaviour would be the same for clicking or setting the indicator through the hash! Ok I quickly fix this
