### ISSUE TITLE
5. Results for each indicators in IOGrid

### ISSUE THREAD

**Issue by TheTisiboth** [USEPA/useeio-widgets#32]
5. When there are multiple indicators, please show a value line for each selected indicator for each row.
So the following would include 4 value lines under each commodity title within the center column.
(This is the update Andrew offered to make at the start of the year, but couldn't figure out.)

**Comment by TheTisiboth** [comment]
Should we have just one rank (that summarises the commodity impact overall), or a rank for each result of the commodity?

**Comment by localsite** [comment]
Let's default to both if possible. First the ranking number, followed by a value for each indicator selected (up to 4). If the user selects more than 4 indicators, just show the ranking number. The 1 to 4 indicators listed would each show the simple type (kilograms, etc.). Thanks!

**Comment by TheTisiboth** [comment]
So I am going to limit it to 4 indicators, but then is the IOGrid displaying what you were expecting, for the case where we are just displaying one overall rank for each commodity (regardless of the number of indicators selected?)

Then, for the case where we want to display a rank for each selected indicators, I may gonna change the Table structure, so the rank column would be directly after the commodity results, and the slider column would be the last one, so we can see directly one commodity result and then the associated rank. Is that what you want?
Thanks!

**Comment by localsite** [comment]
I'm assuming the overall rank would be based on the indicators selected.
If only one indicator is selected, avoid showing the overall rank. (So we'd jump from 1 to 3 sub-rows when a second indicator is added.)

I think we should avoid adding new columns (to the right of titles) because of limited screen width. Place the rank below the title as a sub-row, followed by up to 4 indicators (each on it's own sub-row).  These sub-rows could reside in a div with the same css class, so we can toggle them all off to shorten the displayed list.

**Comment by TheTisiboth** [comment]
Update : remove the 4 indicators limit

**Comment by localsite** [comment]
For the red bars in the commodities column, when rolling over show the rank value used to sort the column?

This is similar to how rolling over the red bars in the upstream and downstream columns reveals a sort value. Those are currently the same as the visible row values. Later we can sort options to the upstream and downstream columns.

**Comment by TheTisiboth** [comment]
So it would be better to display the real value, the rank, on hover over the red bar, isn't it ?

**Comment by ModelGeorgia** [comment]
When in doubt, show both.

(The percent could be in parenthesis after the real value.)

**Comment by LorenHeyns** [comment]
Can you display both the value and the percentage (in parenthesis) when hovering over the red bar?

No text appears when hovering if there are 2 or more indicators...
https://thetisiboth.github.io/useeio-widget-builds/slider.html#indicators=ENRG,VADD&sectors=1111A0&page=1

**Comment by TheTisiboth** [comment]
In fact, the rank value is a percentage, so I can display the percentage, followed by a `%` character, regardless of the number of indicators selected, when hovering over the red bar.
