### ISSUE TITLE
11. More distinct color variation on Heatmap

### ISSUE THREAD

**Issue by TheTisiboth** [USEPA/useeio-widgets#36]
11. The gradation on JOBS and VADD is very slight. Is it possible to make their color variation more distinct like the other indicators?

The last three VADD values seem to be skewing the gradation of the column:

S00900 - Rest of the world adjustment = $0.294 
S00300 - Noncomparable imports = $0.00
S00402 - Used and secondhand goods = $0.00

Could the color intensity for these outliers be muted to bring out the gradient for the others (without changing the values displayed in the chart)?  Perhaps always mute $0.00 values.

**Comment by TheTisiboth** [comment]
I tried using a sqare root growth, instead of a linear growth. As a result, the little value gets more dark more quicker. Is it enough like this ?

**Comment by ModelGeorgia** [comment]
Nice, the gradation looks better for all the columns!

Both JOBS and VADD still need to have the top outlier(s) muted to bring up distinction.
Could the solid waste Value Added value of $8.844 be wrong? All the other VADD values are below $1.05.

Please move the decimal on the jobs so they don't all appear as 0.000 jobs.

When the measurement type is $, place the symbol at the front of the value: $8.844

**Comment by TheTisiboth** [comment]
I already moved the decimal for the Jobs: https://thetisiboth.github.io/useeio-widget-builds/sector_list.html#view=mosaic
You don't see it ?

**Comment by TheTisiboth** [comment]
> Both JOBS and VADD still need to have the top outlier(s) muted to bring up distinction.

How would you do it ?
For instance, we could take the max value as the X% biggest value , but then how do we colorise the value which are above this new max value ?

**Comment by localsite** [comment]
Create an object containing the outliers and their values for each indicator column.
Populate this object only once, when the data is initially loaded.

To set the color scale for the sort, reduce the outlier values to start at 25% above the next closest value.

Using JOBS as an example, reduce 0.0001 and 0.0002 so the closest outlier value (0.0001) is 25% above 0.00003 -- note the additional 0. 

Subtract the lowest outlier (0.0001) from itself and from all the other outliers:

Outlier 0.0001 becomes (0.00003 x 1.25) + (0.0001 - 0.0001) = 0.0000375
Outlier 0.0002 becomes (0.00003 x 1.25) + (0.0002 - 0.0001) = 0.0001375

These modified values will thereby be used to generate the color scale. 
After the color scale is applied, update the displayed values using the original values stored in the object.

Experiment with increasing from 25% to 30% (or more) to see if that helps distinguish the outliers without losing too much of the gradient spread for the other values.

**Comment by modelearth** [comment]
Léo, can you reactivate the more intense color gradation you had briefly. (I sent screenshots of it last week.)  It was for all bars.

**Comment by TheTisiboth** [comment]
Yes of course. I had some issues with updating with the model v2, but now it is fine again.
