### ISSUE TITLE
IOGrid update

### ISSUE THREAD

**Issue by TheTisiboth** [USEPA/useeio-widgets#47]
In the input-output chart, align the checkbox with the commodity title.
Move the slider and red bar into the commodity title row, so the indicator rows below can span the column.

Make the grey bar shorter (3px tall) with bottom:0 so it resides after the text. 
Change it from grey to a light orange: #ffb347

Also good to make the sub-row font smaller, and place the impact title in each sub-row:

**Agriculture and forestry support** 

Jobs Supported: 0.000 Employees

Value Added: 0.729 US Dollars (per $ spent)

Water Use: 0.054 Cubic Meters

"per $ spent" could be inserted for clarity.
Scale of employees needs to be adjusted to show a value > 0.

**Comment by TheTisiboth** [comment]
> Make the grey bar shorter (3px tall) with bottom:0 so it resides after the text.
So the bar should have 3 pixels less in height? 
And then I don't understand what do you mean, and how it should look like. The grey bar should be after the text, like for the red bar (overall rank)?

**Comment by TheTisiboth** [comment]
> place the impact title in each sub-row

What do you mean?

**Comment by localsite** [comment]
From the May 4, 2021 email:

In the input-output chart, 

Make the bar shorter (3px tall) with bottom:0 so it resides after the text (rather than behind the text).
Change it from grey to a light orange: #ffb347
(Note that this differs from the mock-up I sent last week.)

Also, align the checkbox with the commodity title.
Move the slider and red bar into the commodity title row, so the indicator rows below can span the column.

**Comment by localsite** [comment]
![mockup-iogrid](https://user-images.githubusercontent.com/26004239/117344381-54ac9280-ae73-11eb-9d67-db1f5278368b.png)

**Comment by TheTisiboth** [comment]
Ahh thanks for the mockup! Okay lets do it!

**Comment by ModelGeorgia** [comment]
Here's css to align the checkboxes to the top and move the title down 6px:

.MuiDataGrid-root .MuiDataGrid-cellWithRenderer {
    position: relative;
}
.MuiCheckbox-colorSecondary.Mui-checked {
    top: 0px;
    position: absolute;
}
.MuiDataGrid-root .MuiDataGrid-colCell, .MuiDataGrid-root .MuiDataGrid-cell {
    padding: 0px;
}
.MuiButtonBase-root {
   align-items: normal;
}
.MuiGrid-grid-xs-8 {
    padding-top: 6px;
}
Sometimes we may have fewer than 3 columns, so better to use the column name when applying padding-top: 6px;

**Comment by TheTisiboth** [comment]
Oh thanks a lot, I was struggling positioning those checkboxes!
