### ISSUE TITLE
Settings filter broken

### ISSUE THREAD

**Issue by TheTisiboth** [USEPA/useeio-widgets#48]
Something is broken:
- the settings filter doesn't get the year and location (https://thetisiboth.github.io/useeio-widget-builds/filter.html)
It may be due to asynchronous fetch of year and location, that doesn't update the component:
https://github.com/USEPA/useeio-widgets/blob/1326f55c7fb8da020d7ca42a71b34285bc02d802/src/widgets/settings.tsx#L69

However, it is working when we change either the perspective or analyse type because it will cause an update, then we can select the year or the location.

**Comment by localsite** [comment]
Please add the state filter for GAUSEEIO when updating the Location filter.

Recommend using #state=GA in the URL to be consistent and short.

**Comment by TheTisiboth** [comment]
The previous bug is fixed. But I didn't understand your previous message. What is this state about ?

**Comment by localsite** [comment]
We're using state=GA in model.earth. Allows the parameter to be omitted for the US.
location seems good to support future regions that are neither state or country.
