### ISSUE TITLE
Order of heatmap main categories

### ISSUE THREAD

**Issue by localsite** [USEPA/useeio-widgets#49]
Provide a config setting to display the heatmap main categories in the following order:

Economic & Social
Resource Use
Impact Potential
Chemical Releases
Waste Generated

https://thetisiboth.github.io/useeio-widget-builds/sector_list.html?view=mosaic

Call this the the "planning" order (which is focus of economic developers).

Call the existing order the "policy" order.

Later we can make these a preference setting stored as a cookie: 

Indictor sort order:
Policy - Environmental Protection focus
Planning -  Economic Development focus

**Comment by TheTisiboth** [comment]
We can now do it thanks to the configuration parameter `indicators-order`
