### ISSUE TITLE
Update to heatmap legend and column sorting

### ISSUE THREAD

**Issue by localsite** [USEPA/useeio-widgets#52]
Why does the mosaic heatmap list "Fresh fruits and tree nuts" first?

https://thetisiboth.github.io/useeio-widget-builds/sector_list.html#count=100&view=mosaic&showvalues=true&page=1

1. Move text about demand after the chart and update text.

The demand column contains 3 types of values:  

--- : Commodities with no demand values. Other commodities provide their demand.
0.000 : Commodities with demand values less than 0.0005 billion  
1.234 : Commodities with demand values in billions  

2. Split the first column into two columns: The naics "id" and the "name" (or "title"). Make them sortable.

3. Update all the column sorts to toggle between most and least, so the user can view commodities with the least impact.

**Comment by TheTisiboth** [comment]
https://thetisiboth.github.io/useeio-widget-builds/sector_list.html#count=100&view=mosaic,ranking&showvalues=true&page=1
If you look here, you see that `Fresh fruits and tree nuts` has the highest rank. The ranking function was already implemented, I didn't change it. However, I updated the model, this why we have other values than here I guess :
https://msrocka.github.io/useeio-widget-builds/sector_list.html#view=mosaic,ranking

**Comment by TheTisiboth** [comment]
About point 3), what should be the behaviour of the sorting action then? We should toggle from most, least and that's it? Or should we be able to unsort also, as a third state?

**Comment by localsite** [comment]
Good to include a third state (unsort) when there is more then 1 indicator column, and the "unsort" will actually sort by the industries' aggregated ranking within all the visible columns.
