### ISSUE TITLE
Input-Output Filter Popup - Height, Item Names and Page Scroll

### ISSUE THREAD

**Issue by localsite** [USEPA/useeio-widgets#57]
- Reduce top of popup by 50px. (It currently gets covered by page header).
- Rename to "Show Selected Only" and "Show Selected First"
- Place a line above "Alphabetical"
- If easy, allow rest of page to still scroll when the popup is open.

Example of header overlap and scroll issue:
https://model.earth/localsite/info/

I was not able to figure out how to modify the popup's z-index to overlap the page header, but that's another possible approach.

**Comment by TheTisiboth** [comment]
For some reason, it seems not doable to allow the scroll on the rest of the page
